# Generated by Django 4.2.7 on 2023-11-25 17:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='SMTP server address')),
                ('port', models.IntegerField(default=465, help_text='Connection port')),
                ('login', models.CharField()),
                ('password', models.CharField()),
                ('email_from', models.CharField(help_text='Sender name visible in the email')),
                ('use_ssl', models.BooleanField(default=True, help_text='Use of SSL')),
                ('is_active', models.BooleanField(default=False, help_text='Inbox activity')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, help_text='The value automatically changed upon mailbox update')),
                ('sent', models.PositiveIntegerField(help_text='A property returning the count of messages sent from the mailbox')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject of the message')),
                ('text', models.TextField(help_text='Message content')),
                ('attachment', models.FileField(blank=True, help_text='Attachment to the message', null=True, upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now, help_text='The value automatically changed upon template update')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), help_text='Recipient', size=None)),
                ('cc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), help_text='Recipients of message copies', size=None)),
                ('bcc', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), help_text='Recipients of blind carbon copy of the message', size=None)),
                ('replay_to', models.EmailField(default=None, help_text='Reply-to address for the message recipient', max_length=254)),
                ('sent_date', models.DateTimeField(default=None, help_text='Date sent - a field filled in after sending the message')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mailbox.mailbox')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mailbox.template')),
            ],
        ),
    ]
