# Generated by Django 4.2.7 on 2023-11-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mailbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='send_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
